[package]
name = "yew-noderef-problem"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
gloo-console = "0.2.1"
web-sys = { version = "0.3.55", features = ["HtmlInputElement"] }
yew = { git = "https://github.com/yewstack/yew.git", branch = "master" }
